version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: astrofinance_db
    environment:
      POSTGRES_USER: astrofinance_user
      POSTGRES_PASSWORD: astrofinance_pass
      POSTGRES_DB: astrofinance_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  api:
    build: .
    container_name: astrofinance_api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://astrofinance_user:astrofinance_pass@postgres:5432/astrofinance_db
      ALPHA_VANTAGE_API_KEY: ${ALPHA_VANTAGE_API_KEY}
      NSE_STOCKS: ${NSE_STOCKS:-RELIANCE,TCS,HDFCBANK,INFY,TATASTEEL,SUNPHARMA,ITC,HINDUNILVR,SBIN,BAJFINANCE}
      USE_REAL_MARKET_DATA: ${USE_REAL_MARKET_DATA:-true}
      MARKET_DATA_CACHE_TTL_HOURS: ${MARKET_DATA_CACHE_TTL_HOURS:-1}
      DEEPSEEK_API_KEY: ${DEEPSEEK_API_KEY}
      DEEPSEEK_BASE_URL: ${DEEPSEEK_BASE_URL:-https://api.deepseek.com/v1}
      DEEPSEEK_MODEL: ${DEEPSEEK_MODEL:-deepseek-chat}
      USE_AI_API: ${USE_AI_API:-false}
      USE_REAL_EPHEMERIS: ${USE_REAL_EPHEMERIS:-true}
      EPHEMERIS_PATH: ${EPHEMERIS_PATH:-./ephe}
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:

